name: YAML workflows

on:
  workflow_dispatch:

env:
  DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}

jobs:
  update-workflows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
  
    - name: Databricks CLI
      uses: databricks/setup-cli@main

    - name: Export Databricks Workflows
      run: |
        mkdir -p workflows
        for job_id in 333681960801059 989837549311403 205322105069298 382932430508596; do
          echo "Generating job: $job_id"
          databricks bundle generate job --existing-job-id "$job_id"
        done
        if [ -d "resources/jobs" ]; then
          mv resources/jobs/* workflows/
        fi
        rm -rf resources src

    - name: Create feature branch
      id: create-branch
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git pull
        git add workflows
        git commit --allow-empty -m "Updated Databricks workflows"
        git push