name: YAML workflows

on:
  workflow_dispatch:

env:
  DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}

jobs:
  update-workflows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
  
    - name: Databricks CLI
      uses: databricks/setup-cli@main

    - name: Export Databricks Workflows
      run: |
        mkdir -p workflows
        for job_id in 333681960801059 989837549311403 205322105069298 382932430508596; do
          echo "Generating job: $job_id"
          databricks bundle generate job --existing-job-id "$job_id"
        done
        mv resources/*.yml workflows/ 2>/dev/null || true
        rm -rf resources src

    - name: Create Feature Branch and Raise PR
      run: |
        BASE_BRANCH="main"  # Change this if needed
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        FEATURE_BRANCH="feature-update-${TIMESTAMP}"
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git fetch origin
        git checkout -b "$FEATURE_BRANCH" origin/"$BASE_BRANCH"
        git add workflows/

        if git diff --staged --quiet; then
          echo "No changes detected, skipping commit and PR creation."
          exit 0
        fi

        git commit -m "Automated update for workflows - $TIMESTAMP"
        git push origin "$FEATURE_BRANCH"
        gh pr create --base "$BASE_BRANCH" --head "$FEATURE_BRANCH" --title "Automated Workflows Update" --body "This PR includes the latest updates to workflows."
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    