name: Deploy Framework

on:
  workflow_dispatch:
    inputs:
      environment_var:
        description: 'Environment'
        required: true
        default: 'DEVELOPMENT'
        type: choice
        options:
          - DEVELOPMENT
          - STAGING
          - PRODUCTION

env:
  JFrog_URL: "https://artifacts.companyorg.com"
  ARTIFACTORY_NAME: "generic-local"
  DATABRICKS_HOST_DEVELOPMENT: "https://adb-1513518831488714.14.azuredatabricks.net/" 
  DATABRICKS_HOST_STAGING: "https://adb-1513518831488714.14.azuredatabricks.net/" 
  DATABRICKS_HOST_PRODUCTION: "https://adb-production.azuredatabricks.net"

jobs:
  Deploy_Databricks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set Environment Variables Based on Input
        run: |
          ENV_UPPER=$(echo "${{ github.event.inputs.environment_var }}" | tr '[:lower:]' '[:upper:]')
          echo "ENV_UPPER=$ENV_UPPER" >> $GITHUB_ENV
          
          case "$ENV_UPPER" in
            "DEVELOPMENT")
              echo "DATABRICKS_HOST=${{ env.DATABRICKS_HOST_DEVELOPMENT }}" >> $GITHUB_ENV
              echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN_DEVELOPMENT }}" >> $GITHUB_ENV
              ;;
            "STAGING")
              echo "DATABRICKS_HOST=${{ env.DATABRICKS_HOST_STAGING }}" >> $GITHUB_ENV
              echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN_STAGING }}" >> $GITHUB_ENV
              ;;
            "PRODUCTION")
              echo "DATABRICKS_HOST=${{ env.DATABRICKS_HOST_PRODUCTION }}" >> $GITHUB_ENV
              echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN_PRODUCTION }}" >> $GITHUB_ENV
              ;;
          esac

      - name: Display Set Environment Variables
        run: |
          echo "🔹 Selected Deployment Environment: $ENV_UPPER"
          echo "🔹 DATABRICKS_HOST: $DATABRICKS_HOST"
      
      - name: Replace Host URL in databricks.yml
        run: |
          sed -i "s|\${DATABRICKS_HOST_${ENV_UPPER}}|${DATABRICKS_HOST}|g" databricks.yml
          echo "✅ Updated databricks.yml with correct host"

      - name: Configure Databricks CLI
        uses: databricks/setup-cli@main  
        env:
          DATABRICKS_TOKEN: ${{ env.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ env.DATABRICKS_HOST }}

      - name: Validate Databricks Bundle
        run: |
          echo "🔎 Validating deployment for $ENV_UPPER..."
          databricks bundle validate -t $ENV_UPPER

      - name: Deploy Databricks Bundle
        run: |
          echo "🚀 Deploying to $ENV_UPPER environment..."
          databricks bundle deploy -t $ENV_UPPER
          echo "✅ Deployment to $ENV_UPPER completed successfully!"
