name: Deploy Databricks Asset Bundle using UAMI

on:
  workflow_dispatch: 

env:
  AZURE_CLIENT_ID: 99dc0d70-db76-46f4-97ef-5d564429e145            # UAMI Client ID
  SUBSCRIPTIONID_DEV: 730114f3-3c96-423d-b203-108734964640   # Azure Subscription ID
  DATABRICKS_HOST: https://adb-2059171872983196.16.azuredatabricks.net
  DATABRICKS_CONFIG_PROFILE: uami-profile

permissions:
  id-token: write  
  contents: read

jobs:
  deploy_uai:
    runs-on: ubuntu-latest
    environment: all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login with Federated Identity
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ env.SUBSCRIPTIONID_DEV }}
          audience: api://AzureADTokenExchange

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Configure .databrickscfg for UAMI
        run: |
          mkdir -p ~/.databricks
          cat <<EOF > ~/.databrickscfg
          [${{ env.DATABRICKS_CONFIG_PROFILE }}]
          host = ${{ env.DATABRICKS_HOST }}
          azure_client_id = ${{ env.AZURE_CLIENT_ID }}
          azure_use_msi = true
          EOF
        shell: bash

      - name: Deploy Databricks Asset Bundle
        run: |
          databricks bundle deploy -t dev --profile $DATABRICKS_CONFIG_PROFILE

  Run_notebook:
    runs-on: ubuntu-latest
    needs: deploy_uai
    steps:
      - name: checkout Code
        uses: actions/checkout@v4

      - name: Databricks CLI
        uses: databricks/setup-cli@main
  
      - name: Configure .databrickscfg for UAMI
        run: |
          mkdir -p ~/.databricks
          cat <<EOF > ~/.databrickscfg
          [${{ env.DATABRICKS_CONFIG_PROFILE }}]
          host = ${{ env.DATABRICKS_HOST }}
          azure_client_id = ${{ env.AZURE_CLIENT_ID }}
          azure_use_msi = true
          EOF
        shell: bash

      - name: Run Databricks notebook
        uses: databricks/run-notebook@v0
        with:
          workspace-notebook-path: /Workspace/Code/hanuman/files/notebooks/test
          databricks-host: ${{ env.DATABRICKS_HOST }}
          databricks-token: ${{ secrets.UAMI_TOKEN }}
          new-cluster-json: |
            {
              "autoscale": {
                "min_workers": 1,
                "max_workers": 2
              },
                "spark_version": "15.4.x-scala2.12",
                "instance_pool_id": "0724-135755-hokey70-pool-mevy7h5u",
                "driver_instance_pool_id": "0724-135849-forts23-pool-0l4qyv8i",
                "data_security_mode": "SINGLE_USER"
            } 
