name: Deploy Databricks Asset Bundle using UAMI

on:
  workflow_dispatch: 

env:
  AZURE_CLIENT_ID: 99dc0d70-db76-46f4-97ef-5d564429e145            # UAMI Client ID
  SUBSCRIPTIONID_DEV: 730114f3-3c96-423d-b203-108734964640   # Azure Subscription ID
  DATABRICKS_HOST: https://adb-2059171872983196.16.azuredatabricks.net
  DATABRICKS_CONFIG_PROFILE: uami-profile

permissions:
  id-token: write  
  contents: read

jobs:
  deploy_uai:
    runs-on: ubuntu-latest
    environment: all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login with Federated Identity
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ env.SUBSCRIPTIONID_DEV }}
          auth-type: IDENTITY

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Configure .databrickscfg for UAMI
        run: |
          mkdir -p ~/.databricks
          cat <<EOF > ~/.databrickscfg
          [${{ env.DATABRICKS_CONFIG_PROFILE }}]
          host = ${{ env.DATABRICKS_HOST }}
          azure_client_id = ${{ env.AZURE_CLIENT_ID }}
          azure_use_msi = true
          EOF
        shell: bash

      - name: Deploy Databricks Asset Bundle
        run: |
          databricks bundle deploy -t dev --profile $DATABRICKS_CONFIG_PROFILE
