name: Update Databricks Workflows

on:
  workflow_dispatch:

env:
  DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}

jobs:
  update-workflows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
  
    - name: Databricks CLI
      uses: databricks/setup-cli@main

    - name: Export Databricks Workflows
      run: |
        mkdir -p workflows
        for job_id in $(databricks jobs list --output JSON | jq -r '.[].job_id'); do
          job_name=$(databricks jobs get "$job_id" | jq -r '.settings.name' | tr ' ' '_' | tr -d '[:punct:]')
          echo "Exporting job: $job_name ($job_id)"
          databricks jobs get "$job_id" > "workflows/${job_name}.json"
        done

    - name: Create feature branch
      id: create-branch
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git pull
        git add workflows
        git commit --allow-empty -m "Updated Databricks workflows"
        git push
