name: Update Databricks Workflows

on:
  workflow_dispatch:

env:
  DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}

jobs:
  update-workflows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
  
    - name: Databricks CLI
      uses: databricks/setup-cli@main

    - name: Export Databricks Workflows
      run: |
        mkdir -p workflows
        for job_id in $(databricks jobs list --output JSON | jq -r '.[].job_id'); do
          job_name=$(databricks jobs get "$job_id" | jq -r '.settings.name' | tr ' ' '_' | tr -d '[:punct:]')
          echo "Exporting job: $job_name ($job_id)"
          databricks jobs get "$job_id" > "workflows/${job_name}.json"
        done

    - name: Create feature branch
      id: create-branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        BRANCH_NAME="workflows-update-$(date +%s)"
        git checkout -b "$BRANCH_NAME"
        echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Commit changes
      run: |
        git add workflows
        git commit -m "Updated Databricks workflows"

    - name: Push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git remote set-url origin https://x-access-token:$GH_PAT@github.com/${{ github.repository }}
        git push origin ${{ env.branch_name }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GH_PAT }}
        branch: ${{ env.branch_name }}
        base: main
        title: "Update Databricks Workflows"
        body: "Automated PR to update Databricks workflows."
        labels: "workflows-update"